module.exports = {
  PORT: process.env.PORT || 3000,
  ADMIN_SECRET: process.env.ADMIN_SECRET || 'admin123',
  GAME: {
    DEFAULT_USER_BALANCE: 30000.00,
    CURRENCY: 'PKR',
    HOUSE_EDGE: 0.03,
    DEFAULT_RTP_PERCENT: 96,
    INSTANT_CRASH_CHANCE: 0.04,
    MIN_MULTIPLIER: 1.00,
    MAX_MULTIPLIER: 1000.00,
    WAIT_DURATION_SEC: 5,
    CRASH_PAUSE_SEC: 3,
    TICK_INTERVAL_MS: 60
  }
};
